// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/ingest.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value             float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Tags              []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Point) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Point) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *Point) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AgentReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	TotalMemory   int64                  `protobuf:"varint,6,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	DiskSize      int64                  `protobuf:"varint,8,opt,name=disk_size,json=diskSize,proto3" json:"disk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReport) Reset() {
	*x = AgentReport{}
	mi := &file_proto_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReport) ProtoMessage() {}

func (x *AgentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReport.ProtoReflect.Descriptor instead.
func (*AgentReport) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *AgentReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentReport) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentReport) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentReport) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *AgentReport) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *AgentReport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentReport) GetDiskSize() int64 {
	if x != nil {
		return x.DiskSize
	}
	return 0
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Points        []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *Batch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Batch) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_proto_ingest_proto protoreflect.FileDescriptor

const file_proto_ingest_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ingest.proto\x12\x10kanshi.ingest.v1\"u\n" +
	"\x05Point\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xdf\x01\n" +
	"\vAgentReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12!\n" +
	"\ftotal_memory\x18\x06 \x01(\x03R\vtotalMemory\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1b\n" +
	"\tdisk_size\x18\b \x01(\x03R\bdiskSize\"S\n" +
	"\x05Batch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12/\n" +
	"\x06points\x18\x02 \x03(\v2\x17.kanshi.ingest.v1.PointR\x06points\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted2\x93\x01\n" +
	"\rIngestService\x12=\n" +
	"\vIngestBatch\x12\x17.kanshi.ingest.v1.Batch\x1a\x15.kanshi.ingest.v1.Ack\x12C\n" +
	"\vReportAgent\x12\x1d.kanshi.ingest.v1.AgentReport\x1a\x15.kanshi.ingest.v1.AckB3Z1github.com/kanshi-dev/core/proto/ingest/v1;ingestb\x06proto3"

var (
	file_proto_ingest_proto_rawDescOnce sync.Once
	file_proto_ingest_proto_rawDescData []byte
)

func file_proto_ingest_proto_rawDescGZIP() []byte {
	file_proto_ingest_proto_rawDescOnce.Do(func() {
		file_proto_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingest_proto_rawDesc), len(file_proto_ingest_proto_rawDesc)))
	})
	return file_proto_ingest_proto_rawDescData
}

var file_proto_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ingest_proto_goTypes = []any{
	(*Point)(nil),       // 0: kanshi.ingest.v1.Point
	(*AgentReport)(nil), // 1: kanshi.ingest.v1.AgentReport
	(*Batch)(nil),       // 2: kanshi.ingest.v1.Batch
	(*Ack)(nil),         // 3: kanshi.ingest.v1.Ack
}
var file_proto_ingest_proto_depIdxs = []int32{
	0, // 0: kanshi.ingest.v1.Batch.points:type_name -> kanshi.ingest.v1.Point
	2, // 1: kanshi.ingest.v1.IngestService.IngestBatch:input_type -> kanshi.ingest.v1.Batch
	1, // 2: kanshi.ingest.v1.IngestService.ReportAgent:input_type -> kanshi.ingest.v1.AgentReport
	3, // 3: kanshi.ingest.v1.IngestService.IngestBatch:output_type -> kanshi.ingest.v1.Ack
	3, // 4: kanshi.ingest.v1.IngestService.ReportAgent:output_type -> kanshi.ingest.v1.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ingest_proto_init() }
func file_proto_ingest_proto_init() {
	if File_proto_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingest_proto_rawDesc), len(file_proto_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingest_proto_goTypes,
		DependencyIndexes: file_proto_ingest_proto_depIdxs,
		MessageInfos:      file_proto_ingest_proto_msgTypes,
	}.Build()
	File_proto_ingest_proto = out.File
	file_proto_ingest_proto_goTypes = nil
	file_proto_ingest_proto_depIdxs = nil
}
