// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAgents = `-- name: ListAgents :many
SELECT
    agent_id AS "agentId",
    hostname AS "hostName",
    os AS "os",
    platform,
    arch AS "arch",
    cpu_cores AS "cpuCores",
    total_memory AS "totalMemory",
    version AS "version",
    last_seen AS "lastSeen",
    disk_size AS "diskSize"
FROM agents
ORDER BY last_seen DESC
`

type ListAgentsRow struct {
	AgentId     string             `json:"agentId"`
	HostName    string             `json:"hostName"`
	Os          string             `json:"os"`
	Platform    string             `json:"platform"`
	Arch        string             `json:"arch"`
	CpuCores    int32              `json:"cpuCores"`
	TotalMemory int64              `json:"totalMemory"`
	Version     string             `json:"version"`
	LastSeen    pgtype.Timestamptz `json:"lastSeen"`
	DiskSize    int64              `json:"diskSize"`
}

func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.AgentId,
			&i.HostName,
			&i.Os,
			&i.Platform,
			&i.Arch,
			&i.CpuCores,
			&i.TotalMemory,
			&i.Version,
			&i.LastSeen,
			&i.DiskSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentHeartbeat = `-- name: UpsertAgentHeartbeat :exec
UPDATE agents
SET last_seen = NOW()
WHERE agent_id = $1
`

func (q *Queries) UpsertAgentHeartbeat(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, upsertAgentHeartbeat, agentID)
	return err
}

const upsertAgentReport = `-- name: UpsertAgentReport :exec
INSERT INTO agents (
    agent_id,
    hostname,
    os,
    platform,
    arch,
    cpu_cores,
    total_memory,
    disk_size,
    version,
    last_seen
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW())
ON CONFLICT (agent_id)
    DO UPDATE SET
                  hostname = EXCLUDED.hostname,
                  os = EXCLUDED.os,
                  platform = EXCLUDED.platform,
                  disk_size = EXCLUDED.disk_size,
                  last_seen = NOW(),
                  arch = EXCLUDED.arch,
                  cpu_cores = EXCLUDED.cpu_cores,
                  total_memory = EXCLUDED.total_memory,
                  version = EXCLUDED.version
`

type UpsertAgentReportParams struct {
	AgentID     string `json:"agent_id"`
	Hostname    string `json:"hostname"`
	Os          string `json:"os"`
	Platform    string `json:"platform"`
	Arch        string `json:"arch"`
	CpuCores    int32  `json:"cpu_cores"`
	TotalMemory int64  `json:"total_memory"`
	DiskSize    int64  `json:"disk_size"`
	Version     string `json:"version"`
}

func (q *Queries) UpsertAgentReport(ctx context.Context, arg UpsertAgentReportParams) error {
	_, err := q.db.Exec(ctx, upsertAgentReport,
		arg.AgentID,
		arg.Hostname,
		arg.Os,
		arg.Platform,
		arg.Arch,
		arg.CpuCores,
		arg.TotalMemory,
		arg.DiskSize,
		arg.Version,
	)
	return err
}
