// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package db

import (
	"context"
)

const listAgents = `-- name: ListAgents :many
SELECT
    agent_id,
    last_seen
FROM agents
ORDER BY last_seen DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(&i.AgentID, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentHeartbeat = `-- name: UpsertAgentHeartbeat :exec
INSERT INTO agents (agent_id, last_seen)
VALUES ($1, NOW())
ON CONFLICT (agent_id)
    DO UPDATE SET last_seen = EXCLUDED.last_seen
`

func (q *Queries) UpsertAgentHeartbeat(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, upsertAgentHeartbeat, agentID)
	return err
}
