// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (name, metric, comparator, threshold, agent_id, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, metric, comparator, threshold, agent_id, enabled, created_at, updated_at
`

type CreateAlertRuleParams struct {
	Name       string      `json:"name"`
	Metric     string      `json:"metric"`
	Comparator string      `json:"comparator"`
	Threshold  float64     `json:"threshold"`
	AgentID    pgtype.Text `json:"agent_id"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.Name,
		arg.Metric,
		arg.Comparator,
		arg.Threshold,
		arg.AgentID,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metric,
		&i.Comparator,
		&i.Threshold,
		&i.AgentID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :execrows
DELETE
FROM alert_rules
WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlertRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, name, metric, comparator, threshold, agent_id, enabled, created_at, updated_at
FROM alert_rules
WHERE id = $1
`

func (q *Queries) GetAlertRule(ctx context.Context, id int64) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metric,
		&i.Comparator,
		&i.Threshold,
		&i.AgentID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestEventPerTarget = `-- name: GetLatestEventPerTarget :many
SELECT DISTINCT ON (rule_id, agent_id) rule_id,
                                       agent_id,
                                       state
FROM alert_events
ORDER BY rule_id, agent_id, created_at DESC
`

type GetLatestEventPerTargetRow struct {
	RuleID  int64  `json:"rule_id"`
	AgentID string `json:"agent_id"`
	State   string `json:"state"`
}

// Prior firing/resolved state per (rule, agent). Restart-safe: this table is
// the persisted alert state.
func (q *Queries) GetLatestEventPerTarget(ctx context.Context) ([]GetLatestEventPerTargetRow, error) {
	rows, err := q.db.Query(ctx, getLatestEventPerTarget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestEventPerTargetRow
	for rows.Next() {
		var i GetLatestEventPerTargetRow
		if err := rows.Scan(&i.RuleID, &i.AgentID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMetricPerAgent = `-- name: GetLatestMetricPerAgent :many
SELECT DISTINCT ON (agent_id) agent_id AS "agentId",
                              value
FROM metrics
WHERE name = $1
  AND ts > NOW() - INTERVAL '5 minutes'
ORDER BY agent_id, ts DESC
`

type GetLatestMetricPerAgentRow struct {
	AgentId string  `json:"agentId"`
	Value   float64 `json:"value"`
}

// Latest value per agent for one metric within a freshness window, so the
// evaluator never fires on stale data.
func (q *Queries) GetLatestMetricPerAgent(ctx context.Context, name string) ([]GetLatestMetricPerAgentRow, error) {
	rows, err := q.db.Query(ctx, getLatestMetricPerAgent, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMetricPerAgentRow
	for rows.Next() {
		var i GetLatestMetricPerAgentRow
		if err := rows.Scan(&i.AgentId, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlertEvent = `-- name: InsertAlertEvent :one
INSERT INTO alert_events (rule_id, agent_id, state, value, webhook_status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, rule_id, agent_id, state, value, created_at, webhook_status, webhook_error
`

type InsertAlertEventParams struct {
	RuleID        int64   `json:"rule_id"`
	AgentID       string  `json:"agent_id"`
	State         string  `json:"state"`
	Value         float64 `json:"value"`
	WebhookStatus string  `json:"webhook_status"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, insertAlertEvent,
		arg.RuleID,
		arg.AgentID,
		arg.State,
		arg.Value,
		arg.WebhookStatus,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.AgentID,
		&i.State,
		&i.Value,
		&i.CreatedAt,
		&i.WebhookStatus,
		&i.WebhookError,
	)
	return i, err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT e.id,
       e.rule_id        AS "ruleId",
       r.name           AS "ruleName",
       r.metric         AS "metric",
       e.agent_id       AS "agentId",
       e.state          AS "state",
       e.value          AS "value",
       e.created_at     AS "createdAt",
       e.webhook_status AS "webhookStatus",
       e.webhook_error  AS "webhookError"
FROM (SELECT DISTINCT ON (rule_id, agent_id) id, rule_id, agent_id, state, value, created_at, webhook_status, webhook_error
      FROM alert_events
      ORDER BY rule_id, agent_id, created_at DESC) e
         JOIN alert_rules r ON r.id = e.rule_id
WHERE e.state = 'firing'
ORDER BY e.created_at DESC
`

type ListActiveAlertsRow struct {
	ID            int64              `json:"id"`
	RuleId        int64              `json:"ruleId"`
	RuleName      string             `json:"ruleName"`
	Metric        string             `json:"metric"`
	AgentId       string             `json:"agentId"`
	State         string             `json:"state"`
	Value         float64            `json:"value"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	WebhookStatus string             `json:"webhookStatus"`
	WebhookError  pgtype.Text        `json:"webhookError"`
}

func (q *Queries) ListActiveAlerts(ctx context.Context) ([]ListActiveAlertsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAlertsRow
	for rows.Next() {
		var i ListActiveAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleId,
			&i.RuleName,
			&i.Metric,
			&i.AgentId,
			&i.State,
			&i.Value,
			&i.CreatedAt,
			&i.WebhookStatus,
			&i.WebhookError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT e.id,
       e.rule_id        AS "ruleId",
       r.name           AS "ruleName",
       r.metric         AS "metric",
       e.agent_id       AS "agentId",
       e.state          AS "state",
       e.value          AS "value",
       e.created_at     AS "createdAt",
       e.webhook_status AS "webhookStatus",
       e.webhook_error  AS "webhookError"
FROM alert_events e
         JOIN alert_rules r ON r.id = e.rule_id
ORDER BY e.created_at DESC
LIMIT $1
`

type ListAlertEventsRow struct {
	ID            int64              `json:"id"`
	RuleId        int64              `json:"ruleId"`
	RuleName      string             `json:"ruleName"`
	Metric        string             `json:"metric"`
	AgentId       string             `json:"agentId"`
	State         string             `json:"state"`
	Value         float64            `json:"value"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	WebhookStatus string             `json:"webhookStatus"`
	WebhookError  pgtype.Text        `json:"webhookError"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, lim int32) ([]ListAlertEventsRow, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertEventsRow
	for rows.Next() {
		var i ListAlertEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleId,
			&i.RuleName,
			&i.Metric,
			&i.AgentId,
			&i.State,
			&i.Value,
			&i.CreatedAt,
			&i.WebhookStatus,
			&i.WebhookError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, metric, comparator, threshold, agent_id, enabled, created_at, updated_at
FROM alert_rules
ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metric,
			&i.Comparator,
			&i.Threshold,
			&i.AgentID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, name, metric, comparator, threshold, agent_id, enabled, created_at, updated_at
FROM alert_rules
WHERE enabled = TRUE
`

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metric,
			&i.Comparator,
			&i.Threshold,
			&i.AgentID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name       = $1,
    metric     = $2,
    comparator = $3,
    threshold  = $4,
    agent_id   = $5,
    enabled    = $6,
    updated_at = NOW()
WHERE id = $7
RETURNING id, name, metric, comparator, threshold, agent_id, enabled, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	Name       string      `json:"name"`
	Metric     string      `json:"metric"`
	Comparator string      `json:"comparator"`
	Threshold  float64     `json:"threshold"`
	AgentID    pgtype.Text `json:"agent_id"`
	Enabled    bool        `json:"enabled"`
	ID         int64       `json:"id"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.Name,
		arg.Metric,
		arg.Comparator,
		arg.Threshold,
		arg.AgentID,
		arg.Enabled,
		arg.ID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metric,
		&i.Comparator,
		&i.Threshold,
		&i.AgentID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventWebhookStatus = `-- name: UpdateEventWebhookStatus :exec
UPDATE alert_events
SET webhook_status = $1,
    webhook_error  = $2
WHERE id = $3
`

type UpdateEventWebhookStatusParams struct {
	WebhookStatus string      `json:"webhook_status"`
	WebhookError  pgtype.Text `json:"webhook_error"`
	ID            int64       `json:"id"`
}

func (q *Queries) UpdateEventWebhookStatus(ctx context.Context, arg UpdateEventWebhookStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventWebhookStatus, arg.WebhookStatus, arg.WebhookError, arg.ID)
	return err
}
