// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMetricsByTimeRange = `-- name: GetMetricsByTimeRange :many
SELECT
    agent_id,
    name,
    ROUND(value::numeric, 2)::float8 AS value,
    ts,
    tags
FROM metrics
WHERE agent_id = $1
  AND name = $2
  AND ts BETWEEN $3 AND $4
ORDER BY ts DESC
LIMIT 100
`

type GetMetricsByTimeRangeParams struct {
	AgentID string             `json:"agent_id"`
	Name    string             `json:"name"`
	FromTs  pgtype.Timestamptz `json:"from_ts"`
	ToTs    pgtype.Timestamptz `json:"to_ts"`
}

type GetMetricsByTimeRangeRow struct {
	AgentID string             `json:"agent_id"`
	Name    string             `json:"name"`
	Value   float64            `json:"value"`
	Ts      pgtype.Timestamptz `json:"ts"`
	Tags    []string           `json:"tags"`
}

func (q *Queries) GetMetricsByTimeRange(ctx context.Context, arg GetMetricsByTimeRangeParams) ([]GetMetricsByTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, getMetricsByTimeRange,
		arg.AgentID,
		arg.Name,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMetricsByTimeRangeRow
	for rows.Next() {
		var i GetMetricsByTimeRangeRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Name,
			&i.Value,
			&i.Ts,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMetricsBatch = `-- name: InsertMetricsBatch :exec
INSERT INTO metrics (
    agent_id,
    name,
    value,
    ts,
    tags
)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::double precision[]),
    unnest($4::timestamptz[]),
    $5::text[][]
`

type InsertMetricsBatchParams struct {
	AgentIDS   []string             `json:"agent_id_s"`
	Names      []string             `json:"names"`
	Values     []float64            `json:"values"`
	Timestamps []pgtype.Timestamptz `json:"timestamps"`
	Tags       [][]string           `json:"tags"`
}

func (q *Queries) InsertMetricsBatch(ctx context.Context, arg InsertMetricsBatchParams) error {
	_, err := q.db.Exec(ctx, insertMetricsBatch,
		arg.AgentIDS,
		arg.Names,
		arg.Values,
		arg.Timestamps,
		arg.Tags,
	)
	return err
}
