// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMetricsBatch = `-- name: InsertMetricsBatch :exec
INSERT INTO metrics (
    agent_id,
    name,
    value,
    ts,
    tags
)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::double precision[]),
    unnest($4::timestamptz[]),
    $5::text[][]
`

type InsertMetricsBatchParams struct {
	AgentIDS   []string             `json:"agent_id_s"`
	Names      []string             `json:"names"`
	Values     []float64            `json:"values"`
	Timestamps []pgtype.Timestamptz `json:"timestamps"`
	Tags       [][]string           `json:"tags"`
}

func (q *Queries) InsertMetricsBatch(ctx context.Context, arg InsertMetricsBatchParams) error {
	_, err := q.db.Exec(ctx, insertMetricsBatch,
		arg.AgentIDS,
		arg.Names,
		arg.Values,
		arg.Timestamps,
		arg.Tags,
	)
	return err
}
