// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID  string             `json:"agent_id"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
}

type Metric struct {
	AgentID string             `json:"agent_id"`
	Name    string             `json:"name"`
	Value   float64            `json:"value"`
	Ts      pgtype.Timestamptz `json:"ts"`
	Tags    []string           `json:"tags"`
}
