// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID     string             `json:"agent_id"`
	Hostname    string             `json:"hostname"`
	Os          string             `json:"os"`
	Platform    string             `json:"platform"`
	Arch        string             `json:"arch"`
	CpuCores    int32              `json:"cpu_cores"`
	TotalMemory int64              `json:"total_memory"`
	DiskSize    int64              `json:"disk_size"`
	Version     string             `json:"version"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
}

type AlertEvent struct {
	ID            int64              `json:"id"`
	RuleID        int64              `json:"rule_id"`
	AgentID       string             `json:"agent_id"`
	State         string             `json:"state"`
	Value         float64            `json:"value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WebhookStatus string             `json:"webhook_status"`
	WebhookError  pgtype.Text        `json:"webhook_error"`
}

type AlertRule struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Metric     string             `json:"metric"`
	Comparator string             `json:"comparator"`
	Threshold  float64            `json:"threshold"`
	AgentID    pgtype.Text        `json:"agent_id"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Metric struct {
	AgentID string             `json:"agent_id"`
	Name    string             `json:"name"`
	Value   float64            `json:"value"`
	Ts      pgtype.Timestamptz `json:"ts"`
	Tags    []string           `json:"tags"`
}
