// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeProfileCapture = `-- name: CompleteProfileCapture :one
WITH expired AS (
    DELETE FROM profile_captures WHERE expires_at <= NOW()
)
UPDATE profile_captures
SET state = 'completed',
    filename = $1,
    content_type = $2,
    artifact = $3,
    error = NULL,
    updated_at = NOW(),
    expires_at = NOW() + INTERVAL '24 hours'
WHERE profile_captures.id = $4
  AND profile_captures.agent_id = $5
  AND state IN ('queued', 'capturing')
  AND expires_at > NOW()
RETURNING id, agent_id, target_name, profile_type, duration_seconds, state, error, filename, content_type, artifact, created_at, updated_at, expires_at
`

type CompleteProfileCaptureParams struct {
	Filename    pgtype.Text `json:"filename"`
	ContentType pgtype.Text `json:"content_type"`
	Artifact    []byte      `json:"artifact"`
	ID          string      `json:"id"`
	AgentID     string      `json:"agent_id"`
}

func (q *Queries) CompleteProfileCapture(ctx context.Context, arg CompleteProfileCaptureParams) (ProfileCapture, error) {
	row := q.db.QueryRow(ctx, completeProfileCapture,
		arg.Filename,
		arg.ContentType,
		arg.Artifact,
		arg.ID,
		arg.AgentID,
	)
	var i ProfileCapture
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TargetName,
		&i.ProfileType,
		&i.DurationSeconds,
		&i.State,
		&i.Error,
		&i.Filename,
		&i.ContentType,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createProfileCapture = `-- name: CreateProfileCapture :one
WITH expired AS (
    DELETE FROM profile_captures WHERE expires_at <= NOW()
)
INSERT INTO profile_captures (
    id, agent_id, target_name, profile_type, duration_seconds
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, agent_id, target_name, profile_type, duration_seconds, state, error, filename, content_type, artifact, created_at, updated_at, expires_at
`

type CreateProfileCaptureParams struct {
	ID              string `json:"id"`
	AgentID         string `json:"agent_id"`
	TargetName      string `json:"target_name"`
	ProfileType     string `json:"profile_type"`
	DurationSeconds int16  `json:"duration_seconds"`
}

func (q *Queries) CreateProfileCapture(ctx context.Context, arg CreateProfileCaptureParams) (ProfileCapture, error) {
	row := q.db.QueryRow(ctx, createProfileCapture,
		arg.ID,
		arg.AgentID,
		arg.TargetName,
		arg.ProfileType,
		arg.DurationSeconds,
	)
	var i ProfileCapture
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TargetName,
		&i.ProfileType,
		&i.DurationSeconds,
		&i.State,
		&i.Error,
		&i.Filename,
		&i.ContentType,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredProfileCaptures = `-- name: DeleteExpiredProfileCaptures :execrows
DELETE FROM profile_captures
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredProfileCaptures(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredProfileCaptures)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failProfileCapture = `-- name: FailProfileCapture :one
WITH expired AS (
    DELETE FROM profile_captures WHERE expires_at <= NOW()
)
UPDATE profile_captures
SET state = 'failed',
    error = $1,
    updated_at = NOW(),
    expires_at = NOW() + INTERVAL '24 hours'
WHERE profile_captures.id = $2
  AND profile_captures.agent_id = $3
  AND state IN ('queued', 'capturing')
  AND expires_at > NOW()
RETURNING id, agent_id, target_name, profile_type, duration_seconds, state, error, filename, content_type, artifact, created_at, updated_at, expires_at
`

type FailProfileCaptureParams struct {
	Error   pgtype.Text `json:"error"`
	ID      string      `json:"id"`
	AgentID string      `json:"agent_id"`
}

func (q *Queries) FailProfileCapture(ctx context.Context, arg FailProfileCaptureParams) (ProfileCapture, error) {
	row := q.db.QueryRow(ctx, failProfileCapture, arg.Error, arg.ID, arg.AgentID)
	var i ProfileCapture
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TargetName,
		&i.ProfileType,
		&i.DurationSeconds,
		&i.State,
		&i.Error,
		&i.Filename,
		&i.ContentType,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getProfileCapture = `-- name: GetProfileCapture :one
WITH expired AS (
    DELETE FROM profile_captures WHERE expires_at <= NOW()
)
SELECT id, agent_id, target_name, profile_type, duration_seconds, state, error, filename, content_type, artifact, created_at, updated_at, expires_at
FROM profile_captures
WHERE profile_captures.id = $1
`

func (q *Queries) GetProfileCapture(ctx context.Context, id string) (ProfileCapture, error) {
	row := q.db.QueryRow(ctx, getProfileCapture, id)
	var i ProfileCapture
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TargetName,
		&i.ProfileType,
		&i.DurationSeconds,
		&i.State,
		&i.Error,
		&i.Filename,
		&i.ContentType,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listProfileCapturesByAgent = `-- name: ListProfileCapturesByAgent :many
WITH expired AS (
    DELETE FROM profile_captures WHERE expires_at <= NOW()
)
SELECT id, agent_id, target_name, profile_type, duration_seconds, state, error, filename, content_type, artifact, created_at, updated_at, expires_at
FROM profile_captures
WHERE profile_captures.agent_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListProfileCapturesByAgentParams struct {
	AgentID string `json:"agent_id"`
	Lim     int32  `json:"lim"`
}

func (q *Queries) ListProfileCapturesByAgent(ctx context.Context, arg ListProfileCapturesByAgentParams) ([]ProfileCapture, error) {
	rows, err := q.db.Query(ctx, listProfileCapturesByAgent, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileCapture
	for rows.Next() {
		var i ProfileCapture
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TargetName,
			&i.ProfileType,
			&i.DurationSeconds,
			&i.State,
			&i.Error,
			&i.Filename,
			&i.ContentType,
			&i.Artifact,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startProfileCapture = `-- name: StartProfileCapture :one
WITH expired AS (
    DELETE FROM profile_captures WHERE expires_at <= NOW()
)
UPDATE profile_captures
SET state = 'capturing', updated_at = NOW()
WHERE profile_captures.id = $1
  AND profile_captures.agent_id = $2
  AND state = 'queued'
  AND expires_at > NOW()
RETURNING id, agent_id, target_name, profile_type, duration_seconds, state, error, filename, content_type, artifact, created_at, updated_at, expires_at
`

type StartProfileCaptureParams struct {
	ID      string `json:"id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) StartProfileCapture(ctx context.Context, arg StartProfileCaptureParams) (ProfileCapture, error) {
	row := q.db.QueryRow(ctx, startProfileCapture, arg.ID, arg.AgentID)
	var i ProfileCapture
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TargetName,
		&i.ProfileType,
		&i.DurationSeconds,
		&i.State,
		&i.Error,
		&i.Filename,
		&i.ContentType,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
