// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTraceSpans = `-- name: GetTraceSpans :many
SELECT trace_id, span_id, parent_span_id, service_name, operation, span_kind, status_code,
       status_message, start_time, end_time, duration_ms, attributes,
       COALESCE(resolved.agent_id, '') AS host_agent_id,
       COALESCE(otel_spans.resource_host_name, resolved.hostname, '') AS host_name
FROM otel_spans
LEFT JOIN LATERAL (
    SELECT agents.agent_id, agents.hostname
    FROM agents
    WHERE agents.agent_id = otel_spans.resource_agent_id
       OR agents.hostname = otel_spans.resource_host_name
    ORDER BY (agents.agent_id = otel_spans.resource_agent_id) DESC, agents.last_seen DESC
    LIMIT 1
) resolved ON TRUE
WHERE trace_id = $1
ORDER BY start_time, span_id
LIMIT 1000
`

type GetTraceSpansRow struct {
	TraceID       string             `json:"trace_id"`
	SpanID        string             `json:"span_id"`
	ParentSpanID  string             `json:"parent_span_id"`
	ServiceName   string             `json:"service_name"`
	Operation     string             `json:"operation"`
	SpanKind      int16              `json:"span_kind"`
	StatusCode    int16              `json:"status_code"`
	StatusMessage string             `json:"status_message"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	DurationMs    float64            `json:"duration_ms"`
	Attributes    []byte             `json:"attributes"`
	HostAgentID   string             `json:"host_agent_id"`
	HostName      string             `json:"host_name"`
}

func (q *Queries) GetTraceSpans(ctx context.Context, traceID string) ([]GetTraceSpansRow, error) {
	rows, err := q.db.Query(ctx, getTraceSpans, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTraceSpansRow
	for rows.Next() {
		var i GetTraceSpansRow
		if err := rows.Scan(
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.ServiceName,
			&i.Operation,
			&i.SpanKind,
			&i.StatusCode,
			&i.StatusMessage,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMs,
			&i.Attributes,
			&i.HostAgentID,
			&i.HostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO otel_logs (ts, service_name, severity, body, trace_id, span_id, attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLogParams struct {
	Ts          pgtype.Timestamptz `json:"ts"`
	ServiceName string             `json:"service_name"`
	Severity    string             `json:"severity"`
	Body        string             `json:"body"`
	TraceID     string             `json:"trace_id"`
	SpanID      string             `json:"span_id"`
	Attributes  []byte             `json:"attributes"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.Exec(ctx, insertLog,
		arg.Ts,
		arg.ServiceName,
		arg.Severity,
		arg.Body,
		arg.TraceID,
		arg.SpanID,
		arg.Attributes,
	)
	return err
}

const insertSpan = `-- name: InsertSpan :exec
INSERT INTO otel_spans (
    trace_id, span_id, parent_span_id, service_name, operation, span_kind, status_code,
    status_message, start_time, end_time, duration_ms, attributes, resource_agent_id,
    resource_host_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT DO NOTHING
`

type InsertSpanParams struct {
	TraceID          string             `json:"trace_id"`
	SpanID           string             `json:"span_id"`
	ParentSpanID     string             `json:"parent_span_id"`
	ServiceName      string             `json:"service_name"`
	Operation        string             `json:"operation"`
	SpanKind         int16              `json:"span_kind"`
	StatusCode       int16              `json:"status_code"`
	StatusMessage    string             `json:"status_message"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	DurationMs       float64            `json:"duration_ms"`
	Attributes       []byte             `json:"attributes"`
	ResourceAgentID  pgtype.Text        `json:"resource_agent_id"`
	ResourceHostName pgtype.Text        `json:"resource_host_name"`
}

func (q *Queries) InsertSpan(ctx context.Context, arg InsertSpanParams) error {
	_, err := q.db.Exec(ctx, insertSpan,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.ServiceName,
		arg.Operation,
		arg.SpanKind,
		arg.StatusCode,
		arg.StatusMessage,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMs,
		arg.Attributes,
		arg.ResourceAgentID,
		arg.ResourceHostName,
	)
	return err
}

const listServiceSummaries = `-- name: ListServiceSummaries :many
SELECT
    service_name,
    COUNT(*)::BIGINT AS request_count,
    COUNT(*) FILTER (WHERE status_code = 2)::BIGINT AS error_count,
    COALESCE(AVG(duration_ms), 0)::DOUBLE PRECISION AS avg_duration_ms,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::DOUBLE PRECISION AS p95_duration_ms,
    COALESCE((
        SELECT jsonb_agg(jsonb_build_object('agentId', host.agent_id, 'hostName', host.host_name)
                         ORDER BY host.host_name, host.agent_id)
        FROM (
            SELECT DISTINCT resolved.agent_id,
                   COALESCE(identity_span.resource_host_name, resolved.hostname) AS host_name
            FROM otel_spans identity_span
            LEFT JOIN LATERAL (
                SELECT agents.agent_id, agents.hostname
                FROM agents
                WHERE agents.agent_id = identity_span.resource_agent_id
                   OR agents.hostname = identity_span.resource_host_name
                ORDER BY (agents.agent_id = identity_span.resource_agent_id) DESC, agents.last_seen DESC
                LIMIT 1
            ) resolved ON TRUE
            WHERE identity_span.service_name = summary_span.service_name
              AND identity_span.start_time >= $1
              AND identity_span.start_time <= $2
              AND (identity_span.resource_host_name IS NOT NULL OR resolved.agent_id IS NOT NULL)
            ORDER BY host_name, resolved.agent_id
            LIMIT 20
        ) host
    ), '[]'::jsonb)::TEXT AS hosts
FROM otel_spans summary_span
WHERE (span_kind = 2 OR parent_span_id = '')
  AND start_time >= $1
  AND start_time <= $2
GROUP BY service_name
ORDER BY service_name
LIMIT $3
`

type ListServiceSummariesParams struct {
	FromTime    pgtype.Timestamptz `json:"from_time"`
	ToTime      pgtype.Timestamptz `json:"to_time"`
	ResultLimit int32              `json:"result_limit"`
}

type ListServiceSummariesRow struct {
	ServiceName   string  `json:"service_name"`
	RequestCount  int64   `json:"request_count"`
	ErrorCount    int64   `json:"error_count"`
	AvgDurationMs float64 `json:"avg_duration_ms"`
	P95DurationMs float64 `json:"p95_duration_ms"`
	Hosts         string  `json:"hosts"`
}

func (q *Queries) ListServiceSummaries(ctx context.Context, arg ListServiceSummariesParams) ([]ListServiceSummariesRow, error) {
	rows, err := q.db.Query(ctx, listServiceSummaries, arg.FromTime, arg.ToTime, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceSummariesRow
	for rows.Next() {
		var i ListServiceSummariesRow
		if err := rows.Scan(
			&i.ServiceName,
			&i.RequestCount,
			&i.ErrorCount,
			&i.AvgDurationMs,
			&i.P95DurationMs,
			&i.Hosts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogs = `-- name: SearchLogs :many
SELECT ts, service_name, severity, body, trace_id, span_id, attributes
FROM otel_logs
WHERE ts >= $1
  AND ts <= $2
  AND ($3::TEXT = '' OR service_name = $3)
  AND ($4::TEXT = '' OR trace_id = $4)
  AND ($5::TEXT = '' OR span_id = $5)
ORDER BY ts DESC
LIMIT $6
`

type SearchLogsParams struct {
	FromTime    pgtype.Timestamptz `json:"from_time"`
	ToTime      pgtype.Timestamptz `json:"to_time"`
	ServiceName string             `json:"service_name"`
	TraceID     string             `json:"trace_id"`
	SpanID      string             `json:"span_id"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) SearchLogs(ctx context.Context, arg SearchLogsParams) ([]OtelLog, error) {
	rows, err := q.db.Query(ctx, searchLogs,
		arg.FromTime,
		arg.ToTime,
		arg.ServiceName,
		arg.TraceID,
		arg.SpanID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OtelLog
	for rows.Next() {
		var i OtelLog
		if err := rows.Scan(
			&i.Ts,
			&i.ServiceName,
			&i.Severity,
			&i.Body,
			&i.TraceID,
			&i.SpanID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTraces = `-- name: SearchTraces :many
SELECT
    trace_id,
    service_name,
    (ARRAY_AGG(operation ORDER BY start_time))[1]::TEXT AS root_operation,
    MIN(start_time)::TIMESTAMPTZ AS start_time,
    MAX(end_time)::TIMESTAMPTZ AS end_time,
    (EXTRACT(EPOCH FROM (MAX(end_time) - MIN(start_time))) * 1000)::DOUBLE PRECISION AS duration_ms,
    MAX(status_code)::SMALLINT AS status_code,
    COUNT(*)::BIGINT AS span_count
FROM otel_spans
WHERE start_time >= $1
  AND start_time <= $2
  AND ($3::TEXT = '' OR service_name = $3)
  AND ($4::TEXT = '' OR trace_id = $4)
GROUP BY trace_id, service_name
HAVING ($5::SMALLINT < 0 OR MAX(status_code) = $5)
   AND ($6::DOUBLE PRECISION <= 0
        OR (EXTRACT(EPOCH FROM (MAX(end_time) - MIN(start_time))) * 1000) >= $6)
ORDER BY MIN(start_time) DESC
LIMIT $7
`

type SearchTracesParams struct {
	FromTime      pgtype.Timestamptz `json:"from_time"`
	ToTime        pgtype.Timestamptz `json:"to_time"`
	ServiceName   string             `json:"service_name"`
	TraceID       string             `json:"trace_id"`
	StatusCode    int16              `json:"status_code"`
	MinDurationMs float64            `json:"min_duration_ms"`
	ResultLimit   int32              `json:"result_limit"`
}

type SearchTracesRow struct {
	TraceID       string             `json:"trace_id"`
	ServiceName   string             `json:"service_name"`
	RootOperation string             `json:"root_operation"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	DurationMs    float64            `json:"duration_ms"`
	StatusCode    int16              `json:"status_code"`
	SpanCount     int64              `json:"span_count"`
}

func (q *Queries) SearchTraces(ctx context.Context, arg SearchTracesParams) ([]SearchTracesRow, error) {
	rows, err := q.db.Query(ctx, searchTraces,
		arg.FromTime,
		arg.ToTime,
		arg.ServiceName,
		arg.TraceID,
		arg.StatusCode,
		arg.MinDurationMs,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTracesRow
	for rows.Next() {
		var i SearchTracesRow
		if err := rows.Scan(
			&i.TraceID,
			&i.ServiceName,
			&i.RootOperation,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMs,
			&i.StatusCode,
			&i.SpanCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
